### ISSUE TITLE
Cannot find module 'new-command' : command-line.js

### ISSUE THREAD

**Issue by Deftwun** [hek/hek#9]
```

C:\Users\PC>npm -v
3.9.5

C:\Users\PC>npm install -g hek/hek
C:\Users\PC\AppData\Roaming\npm\hek -> C:\Users\PC\AppData\Roaming\npm\node_modules\hek\bin\hek
C:\Users\PC\AppData\Roaming\npm
`-- hek@1.3.0  (git://github.com/hek/hek.git#0ff42de573e53cb78fecf51b4852f1e3df54d47d)
  +-- cli-form@0.1.4  (git://github.com/azer/cli-form.git#a8b07261fc955ab2e83bf9f34494b2411c72e11c)
  | +-- cli-qa@2.3.0  (git://github.com/azer/cli-qa.git#554635e9a99dc5bba9d6625dd5a101d8342f83e7)
  | | +-- comma-list@0.0.1  (git://github.com/azer/comma-list.git#bc9886453fedf66b75a553ffc805a170814cef9e)
  | | +-- read-cli-input@1.0.1  (git://github.com/azer/read-cli-input.git#9b722f6f1d943a78e01b885d2bf516f89e8d978f)
  | | | `-- on-key-press@0.0.0  (git://github.com/azer/on-key-press.git#489ee95690f8c0a629a001ae640135a50f00a6c6)
  | | `-- validate-value@0.0.0  (git://github.com/azer/validate-value.git#b741aaa6207e50824eaa1081d40135bb6b5c6bfa)
  | |   `-- new-error@0.0.0  (git://github.com/azer/new-error.git#ed9af6282cba7b4edbe878194737340a0fce9717)
  | +-- config-doc@0.1.0  (git://github.com/azer/config-doc.git#1b3068250a70dcf0f7a055dcb7fd8ec3556dbd98)
  | `-- new-struct@0.1.1  (git://github.com/azer/new-struct.git#167ba7de3382d8e7052c89eeea7ee21aa06e2c49)
  +-- expand-home-dir@0.0.2  (git://github.com/azer/expand-home-dir.git#03e8b998a86833cae1039d2d1e9c188fe5eef040)
  +-- format-text@0.0.3  (git://github.com/azer/format-text.git#84d0f3ab339b6556e1782b360cc145cbf64f1daf)
  +-- install-module@1.1.0  (git://github.com/azer/install-module.git#6bd23d7d1dca9f3f39fb7a86261090d4a3c65662)
  +-- mix-objects@0.0.3  (git://github.com/azer/mix-objects.git#783a48fa6a65b0154ecb8a6c7b281d027b59eb07)
  +-- read-json@1.0.0  (git://github.com/azer/read-json.git#912590f5c406712c20d9fd7ab7fc995a4dcc24fe)
  +-- serial-loop@0.0.1  (git://github.com/azer/serial-loop.git#99c6271f80f075b7db089a1aadc7178a310a4570)
  +-- serially@1.1.0  (git://github.com/azer/serially.git#501f9bf322652b8a48f9d722f25823718349f22c)
  +-- slug-to-title@0.0.2  (git://github.com/azer/slug-to-title.git#93f8f18cccb481ecb712add861338cd275b48911)
  +-- style-format@0.0.0  (git://github.com/azer/style-format.git#c0ce6d80ff953d0df03e2089efb6ccbd167a52d7)
  | `-- ansi-codes@0.0.2  (git://github.com/azer/ansi-codes.git#965c105f9f0dba211cbe5409407204df58a6cc9d)
  +-- to-class-name@0.0.0  (git://github.com/azer/to-class-name.git#02a9cb440b5f1c376c045e778977604e46241742)
  +-- to-slug@0.0.0  (git://github.com/azer/to-slug.git#bf33849ab8c4290364f5235312d3975c5a65ccdb)
  | `-- anglicize@0.0.5  (git://github.com/azer/anglicize.git#c26ad75f16ebfd175ed63c3b236ebafe6872c731)
  `-- variable-name@0.0.2  (git://github.com/azer/variable-name.git#198a414c9ed2d1ecb430f9b439159d58c3fb0a6e)


C:\Users\PC>hek
module.js:327
    throw err;
    ^

Error: Cannot find module 'new-command'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\PC\AppData\Roaming\npm\node_modules\hek\lib\command-line.js:3:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

**Comment by azer** [comment]
@Deftwun fixed! thanks for noticing
